//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery4
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Subject
    {
        public int IDSubject { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public int PersonIDPerson { get; set; }
    
        public virtual Person Person { get; set; }

        public override string ToString()
        {
            return $"{IDSubject} | {Name}";
        }
    }
    
}
